site_name: Maneesh Gupta Nalluru
theme:
  icon:
    logo: material/emoticon-happy-outline
  favicon: images/favicon.png
  name: material
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep orange
      accent: lime
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog

extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nvssmgupta/
    - icon: fontawesome/brands/github
      link: https://github.com/ManeeshGuptaNvss
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/GuptaNvss
copyright: |
  Copyrights &copy; 2024 are reserved for  <a href="https://github.com/ManeeshGuptaNvss"  target="_blank" rel="noopener">Maneesh Gupta Nalluru</a>
